spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://hotthinkrds.cjditpwe7bq8.ap-northeast-2.rds.amazonaws.com:3306/innodb
    username: root
    password: test1234
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    deserialization:
      fail_on_unknown_properties: true #잘못된 값 전달시 BAD_REQUEST 응답

hot-think:
  security:
    jwt:
      token-issuer: zerogone
      token-expiration-time: 7200
      refresh-token-exp-time: 43200
      token-signing-key: test123test456test789

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

