spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://hotthinkrds.cjditpwe7bq8.ap-northeast-2.rds.amazonaws.com:3306/innodb
    username: root
    password: test1234
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    deserialization:
      fail_on_unknown_properties: true #잘못된 값 전달시 BAD_REQUEST 응답
  #파일 업로드 용량 제한 설정
  servlet:
    multipart:
      max-file-size: 5MB #default 1MB
      max-request-size: 20MB #default 10MB
file:
  upload-dir: ./uploads

hot-think:
  security:
    jwt:
      token-issuer: zerogone
      token-expiration-time: 60
      refresh-token-exp-time: 720
      token-signing-key: test123test456test789
      jti: 6969sex
temp:
  path:
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

